openapi: 3.0.0
info:
  title: 'Laravel API'
  version: '1.0'
servers:
  -
    url: 'http://localhost:80'
paths:
  /api/login:
    post:
      tags:
        - Auth
      operationId: a3b306d14572d1f4bd6c064b3233e7b8
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/LoginInput'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                properties:
                  jwtToken: { type: string }
                type: object
  /api/health:
    get:
      tags:
        - health
      summary: 'Check the health of the API'
      operationId: 597094aa531969ea5921dd7d260a15e3
      responses:
        '200':
          description: OK
  /api/todos:
    get:
      tags:
        - Todo
      operationId: 403cd30b0c347e1f4f3cb2550035f43d
      parameters:
        -
          name: userID
          in: query
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Todo'
    post:
      tags:
        - Todo
      operationId: 9cf34bbb55f8bad045cdb2e4f8451890
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateTodoInput'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Todo'
  /api/users:
    get:
      tags:
        - User
      operationId: e029df7ae93012f7cdc7b3062ed22e4e
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
    post:
      tags:
        - User
      operationId: b6af8b6d643a137be615555100cb13af
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserInput'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/User'
components:
  schemas:
    LoginInput:
      required:
        - email
        - password
      properties:
        email:
          type: string
        password:
          type: string
      type: object
    CreateTodoInput:
      required:
        - userID
        - content
      properties:
        userID:
          type: integer
        content:
          type: string
      type: object
    Todo:
      required:
        - todoID
        - userID
        - content
        - createdAt
      properties:
        todoID:
          type: integer
        userID:
          type: integer
        content:
          type: string
        createdAt:
          type: string
          format: date-time
      type: object
    CreateUserInput:
      required:
        - email
        - name
        - password
      properties:
        email:
          type: string
        name:
          type: string
        password:
          type: string
      type: object
    User:
      required:
        - UserID
        - email
        - name
      properties:
        UserID:
          type: integer
        email:
          type: string
        name:
          type: string
      type: object
tags:
  -
    name: Auth
    description: Auth
  -
    name: health
    description: health
  -
    name: Todo
    description: Todo
  -
    name: User
    description: User
