openapi: 3.0.0
info:
  title: 'Laravel API'
  version: '1.0'
servers:
  -
    url: 'http://localhost:80'
paths:
  /api/health:
    get:
      tags:
        - health
      summary: 'Check the health of the API'
      operationId: 597094aa531969ea5921dd7d260a15e3
      responses:
        '200':
          description: OK
tags:
  -
    name: health
    description: health
