openapi: 3.0.0
info:
  title: 'Laravel API'
  version: '1.0'
servers:
  -
    url: 'http://localhost:80'
paths:
  /api/health:
    get:
      tags:
        - health
      summary: 'Check the health of the API'
      operationId: 597094aa531969ea5921dd7d260a15e3
      responses:
        '200':
          description: OK
  /api/users:
    post:
      tags:
        - User
      operationId: 5b6e72f178a035f354aff3d8b9eeb221
      requestBody:
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/CreateUserInput'
      responses:
        '201':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CreateUserOutput'
components:
  schemas:
    CreateUserInput:
      required:
        - email
        - name
        - password
      type: object
    CreateUserOutput:
      required:
        - email
        - name
      type: object
tags:
  -
    name: health
    description: health
  -
    name: User
    description: User
